/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyProject;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static boolean search(ArrayList<Integer> array, int a, int b) {
        System.out.println("Searching...");
        if (array == null) return false;
        
        int count_a = 0;
        for (int i : array) {
          if (i == a) count_a++;
        }

        if(count_a == b) return true;
        else return false;
               
        
      }    
}
